# Generated by Django 4.0.1 on 2022-07-20 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compagnia',
            fields=[
                ('idCompagnia', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Compañia')),
                ('nombreCompagnia', models.CharField(max_length=15, verbose_name='Nombre Compañia')),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('idPersonaje', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Personaje')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('team', models.CharField(max_length=12, verbose_name='Team')),
                ('foto', models.ImageField(null=True, upload_to='personajes')),
                ('compagnia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperHeroesWeb.compagnia')),
            ],
        ),
    ]
